a =prompt("java script is awesome");
b=prompt("enter a value of radius");
document.write("<br> You entered: ",a);
document.write("<br> length: ",a.length);
document.write("<br> uppercase: ",a.toUpperCase());
document.write("<br> lowercase: ",a.toLowerCase());
document.write("<br> substring: ",a.substr(4,7));
document.write("<br> replace: ",a.replace("awesome","fantastic"));
document.write("<br> concatnate: ",a + " and fun");
document.write("<br> 1st index of: ",a.indexOf("a"));
document.write("<br> 1st index of: ",a.lastIndexOf("s"));
document.write("<br>");
document.write("<br> Radius: ",b);
document.write("<br> area: ",Math.PI*b*b);
document.write("<br> round: " , Math.round(3.14159));
document.write("<br> absolute value: " , Math.abs(-10));
document.write("<br> squareroot: " , Math.sqrt(64));
document.write("<br> random: ",Math.round( Math.random()*10));